// frontend-react/src/components/tasks/TaskList.tsx
import { useState, useMemo } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useMyTasks, useDeleteTask, useMarkAsDone } from '@hooks/useTasks';
import { useAuthContext } from '@context/AuthContext';
import {
  STATUS_LABELS, STATUS_BADGE_CLASS, PRIORITY_LABELS, PRIORITY_BADGE_CLASS,
  type TaskStatus,
} from '@app-types/task.types';

/**
 * ══════════════════════════════════════════════════════════════
 *  COMPOSANT — TaskList.tsx (React)
 * ══════════════════════════════════════════════════════════════
 *
 *  Liste des tâches du gestionnaire connecté avec :
 *  → Filtrage par statut (client-side, pas de nouveau appel API)
 *  → Actions : Modifier, Supprimer, Marquer comme fait
 *  → Badges de statut et priorité colorés
 *
 *  DIFFÉRENCE AVEC ANGULAR :
 *  → Angular : @for + signals + computed()
 *  → React   : .map() + useMemo() + useState()
 *
 *  TANSTACK QUERY :
 *  → useMyTasks() gère le loading/error/data automatiquement
 *  → Pas besoin de gérer un state 'isLoading' manuellement
 *
 *  OPTIMISME :
 *  → On n'a pas fait d'optimistic update ici pour la suppression
 *    (comportement plus sûr : attendre la confirmation serveur)
 *  → Pour les KPIs du dashboard Manager, on fait de l'optimistic update
 */

// Options de filtre — correspond aux valeurs backend
const FILTER_OPTIONS: Array<{ value: TaskStatus | 'ALL'; label: string }> = [
  { value: 'ALL',      label: 'Toutes' },
  { value: 'A_FAIRE',  label: STATUS_LABELS.A_FAIRE },
  { value: 'VALIDEE',  label: STATUS_LABELS.VALIDEE },
  { value: 'REJETEE',  label: STATUS_LABELS.REJETEE },
  { value: 'DONE',     label: STATUS_LABELS.DONE },
];

export default function TaskList() {
  const navigate   = useNavigate();
  const { currentUser } = useAuthContext();

  // ── TanStack Query hooks ──────────────────────────────────────
  const { data: tasks, isLoading, isError, error } = useMyTasks();
  const deleteMutation   = useDeleteTask();
  const markDoneMutation = useMarkAsDone();

  // ── État local — filtre de statut ─────────────────────────────
  const [filterStatus, setFilterStatus] = useState<TaskStatus | 'ALL'>('ALL');

  /**
   * useMemo : recalcule filteredTasks seulement quand tasks ou filterStatus change.
   * Équivalent de computed() en Angular.
   */
  const filteredTasks = useMemo(() => {
    if (!tasks) return [];
    if (filterStatus === 'ALL') return tasks;
    return tasks.filter((t) => t.status === filterStatus);
  }, [tasks, filterStatus]);

  // Compteur de tâches en retard — pour l'alerte visuelle
  const overdueCount = useMemo(
    () => tasks?.filter((t) => t.overdue && t.status === 'A_FAIRE').length ?? 0,
    [tasks]
  );

  // ── Handlers ──────────────────────────────────────────────────

  async function handleDelete(id: string, title: string) {
    // Confirmation native du navigateur — Simple, accessible
    if (!window.confirm(`Supprimer la tâche "${title}" ?`)) return;
    try {
      await deleteMutation.mutateAsync(id);
    } catch {
      // L'erreur est affichée via deleteMutation.isError
    }
  }

  async function handleMarkAsDone(id: string) {
    try {
      await markDoneMutation.mutateAsync(id);
    } catch {
      // Idem
    }
  }

  // ── Rendu ─────────────────────────────────────────────────────

  if (isLoading) {
    return (
      <div className="flex justify-center items-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600" />
      </div>
    );
  }

  if (isError) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-red-700">
        Erreur lors du chargement : {(error as Error).message}
      </div>
    );
  }

  return (
    <div className="space-y-6">

      {/* ── En-tête ── */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Mes tâches</h1>
          <p className="text-sm text-gray-500 mt-1">
            Bonjour {currentUser?.name} — {tasks?.length ?? 0} tâche(s)
          </p>
        </div>
        <Link
          to="/tasks/new"
          className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition-colors"
        >
          + Nouvelle tâche
        </Link>
      </div>

      {/* ── Alerte retard ── */}
      {overdueCount > 0 && (
        <div className="bg-red-50 border border-red-300 rounded-lg p-3 flex items-center gap-2 text-red-700">
          <span className="text-lg">⏰</span>
          <span className="font-medium">{overdueCount} tâche(s) en retard !</span>
        </div>
      )}

      {/* ── Filtre par statut ── */}
      <div className="flex gap-2 flex-wrap">
        {FILTER_OPTIONS.map(({ value, label }) => (
          <button
            key={value}
            onClick={() => setFilterStatus(value)}
            className={`px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${
              filterStatus === value
                ? 'bg-blue-600 text-white'
                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
            }`}
          >
            {label}
            {value !== 'ALL' && (
              <span className="ml-1.5 bg-white/30 rounded-full px-1.5">
                {tasks?.filter((t) => t.status === value).length ?? 0}
              </span>
            )}
          </button>
        ))}
      </div>

      {/* ── Liste des tâches ── */}
      {filteredTasks.length === 0 ? (
        <div className="text-center py-16 text-gray-400">
          <p className="text-4xl mb-3">📭</p>
          <p className="font-medium">Aucune tâche {filterStatus !== 'ALL' ? 'dans ce statut' : ''}</p>
        </div>
      ) : (
        <div className="space-y-3">
          {filteredTasks.map((task) => (
            <article
              key={task.id}
              className={`bg-white rounded-lg border p-4 hover:shadow-sm transition-shadow ${
                task.overdue && task.status === 'A_FAIRE' ? 'border-red-300' : 'border-gray-200'
              }`}
            >
              <div className="flex items-start justify-between gap-4">

                {/* ── Infos tâche ── */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h3 className="font-semibold text-gray-900 truncate">{task.title}</h3>

                    {/* Badge statut */}
                    <span className={`inline-block px-2 py-0.5 rounded-full text-xs font-medium ${STATUS_BADGE_CLASS[task.status]}`}>
                      {STATUS_LABELS[task.status]}
                    </span>

                    {/* Badge priorité */}
                    <span className={`inline-block px-2 py-0.5 rounded-full text-xs font-medium ${PRIORITY_BADGE_CLASS[task.priority]}`}>
                      {PRIORITY_LABELS[task.priority]}
                    </span>

                    {/* Badge retard */}
                    {task.overdue && task.status === 'A_FAIRE' && (
                      <span className="inline-block px-2 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-700">
                        En retard
                      </span>
                    )}
                  </div>

                  {/* Description tronquée */}
                  {task.description && (
                    <p className="text-sm text-gray-500 mt-1 truncate">{task.description}</p>
                  )}

                  {/* Métadonnées */}
                  <div className="flex gap-4 mt-2 text-xs text-gray-400">
                    {task.dueDate && (
                      <span>
                        📅 Échéance : {new Date(task.dueDate).toLocaleDateString('fr-FR')}
                      </span>
                    )}
                    {task.rejectionReason && (
                      <span className="text-red-500">
                        Rejeté : {task.rejectionReason}
                      </span>
                    )}
                  </div>
                </div>

                {/* ── Actions ── */}
                <div className="flex gap-2 shrink-0">
                  {/* Modifier — seulement si A_FAIRE ou REJETEE (RG-07) */}
                  {(task.status === 'A_FAIRE' || task.status === 'REJETEE') && (
                    <button
                      onClick={() => navigate(`/tasks/${task.id}/edit`)}
                      className="p-1.5 rounded text-gray-400 hover:text-blue-600 hover:bg-blue-50 transition-colors"
                      title="Modifier"
                    >
                      ✏️
                    </button>
                  )}

                  {/* Marquer comme fait — seulement si VALIDEE */}
                  {task.status === 'VALIDEE' && (
                    <button
                      onClick={() => handleMarkAsDone(task.id)}
                      disabled={markDoneMutation.isPending}
                      className="p-1.5 rounded text-gray-400 hover:text-green-600 hover:bg-green-50 transition-colors disabled:opacity-50"
                      title="Marquer comme terminée"
                    >
                      ✅
                    </button>
                  )}

                  {/* Supprimer — seulement si A_FAIRE (RG-05) */}
                  {task.status === 'A_FAIRE' && (
                    <button
                      onClick={() => handleDelete(task.id, task.title)}
                      disabled={deleteMutation.isPending}
                      className="p-1.5 rounded text-gray-400 hover:text-red-600 hover:bg-red-50 transition-colors disabled:opacity-50"
                      title="Supprimer"
                    >
                      🗑️
                    </button>
                  )}
                </div>
              </div>
            </article>
          ))}
        </div>
      )}
    </div>
  );
}

// frontend-angular/src/app/features/tasks/pages/task-list.component.ts
import {
  Component, OnInit, inject, signal, computed, ChangeDetectionStrategy
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { TaskService } from '@core/services/task.service';
import { AuthService } from '@core/auth/auth.service';
import {
  Task, TaskStatus, TASK_STATUS_LABELS, TASK_STATUS_COLORS,
  PRIORITY_LABELS, PRIORITY_COLORS
} from '@core/models/task.model';

/**
 * ══════════════════════════════════════════════════════════════
 *  COMPOSANT — TaskListComponent
 * ══════════════════════════════════════════════════════════════
 *
 *  Page principale : liste des tâches avec filtrage par statut.
 *
 *  STANDALONE COMPONENT (Angular 14+) :
 *  → standalone: true → pas besoin de NgModule
 *  → imports: [] → déclare les dépendances directement dans le composant
 *  → C'est le modèle recommandé depuis Angular 17
 *
 *  SIGNALS ANGULAR 20 :
 *  → signal<T>() : valeur réactive (équivalent à useState en React)
 *  → computed(() => ...) : valeur dérivée recalculée automatiquement
 *  → Avantage vs Observables : pas de subscribe, syntaxe synchrone
 *
 *  CHANGEDETECTIONSTRATEGY.ONPUSH :
 *  → Angular ne re-rend le composant que quand :
 *    - Un @Input change (référence)
 *    - Un Observable émet (async pipe)
 *    - Un Signal change
 *    - changeDetectorRef.markForCheck() est appelé
 *  → Beaucoup plus performant que la stratégie Default (vérification à chaque tick)
 *  → Possible uniquement avec des données immuables et des Signals/Observables
 *
 *  GESTION D'ÉTAT LOCALE (sans NgRx) :
 *  → tasks : signal contenant la liste des tâches
 *  → loading : signal boolean pour l'état de chargement
 *  → error : signal pour les messages d'erreur
 *  → filterStatus : signal pour le filtre actif
 *  → filteredTasks : computed → dérivé de tasks + filterStatus
 *
 *  POURQUOI PAS NgRx STORE ICI ?
 *  → NgRx est utile pour un état global complexe (panier e-commerce, etc.)
 *  → Pour une liste de tâches paginée avec filtres locaux, Signals suffisent
 *  → Plus simple, moins de boilerplate, même performance
 * ══════════════════════════════════════════════════════════════
 */
@Component({
  selector: 'app-task-list',
  standalone: true,
  imports: [CommonModule, RouterLink],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="container mx-auto p-6">

      <!-- ── En-tête ─────────────────────────────────────────── -->
      <div class="flex items-center justify-between mb-6">
        <div>
          <h1 class="text-2xl font-bold text-gray-900">
            {{ isGestionnaire() ? 'Mes tâches' : 'Tâches de l\'équipe' }}
          </h1>
          <p class="text-sm text-gray-500 mt-1">
            {{ filteredTasks().length }} tâche(s) affichée(s)
            @if (overdueCount() > 0) {
              <span class="ml-2 text-red-600 font-medium">
                ⚠️ {{ overdueCount() }} en retard
              </span>
            }
          </p>
        </div>

        <!-- Bouton Créer (GESTIONNAIRE uniquement) -->
        @if (canCreateTask()) {
          <a routerLink="/tasks/new"
             class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700
                    transition-colors text-sm font-medium">
            + Nouvelle tâche
          </a>
        }
      </div>

      <!-- ── Filtres par statut ──────────────────────────────── -->
      <div class="flex gap-2 mb-6 overflow-x-auto">
        <button
          (click)="setFilter(null)"
          [class.bg-gray-900]="filterStatus() === null"
          [class.text-white]="filterStatus() === null"
          [class.bg-gray-100]="filterStatus() !== null"
          class="px-3 py-1.5 rounded-full text-sm font-medium transition-colors whitespace-nowrap">
          Tous ({{ tasks().length }})
        </button>

        @for (status of statuses; track status) {
          <button
            (click)="setFilter(status)"
            [class.ring-2]="filterStatus() === status"
            [class]="getStatusColorClass(status)"
            class="px-3 py-1.5 rounded-full text-sm font-medium transition-all whitespace-nowrap">
            {{ getStatusLabel(status) }} ({{ countByStatus(status) }})
          </button>
        }
      </div>

      <!-- ── État de chargement ──────────────────────────────── -->
      @if (loading()) {
        <div class="flex justify-center items-center h-48">
          <div class="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600"></div>
        </div>
      }

      <!-- ── Message d'erreur ────────────────────────────────── -->
      @if (error()) {
        <div class="bg-red-50 border border-red-200 rounded-lg p-4 mb-4">
          <p class="text-red-700 text-sm">{{ error() }}</p>
          <button (click)="reload()" class="mt-2 text-red-600 text-sm underline">
            Réessayer
          </button>
        </div>
      }

      <!-- ── Liste des tâches ────────────────────────────────── -->
      @if (!loading() && !error()) {
        @if (filteredTasks().length === 0) {
          <div class="text-center py-16 text-gray-400">
            <p class="text-4xl mb-3">📋</p>
            <p class="text-lg font-medium">Aucune tâche trouvée</p>
            <p class="text-sm">
              @if (filterStatus()) { Aucune tâche avec le statut "{{ getStatusLabel(filterStatus()!) }}" }
              @else if (canCreateTask()) { Créez votre première tâche ! }
            </p>
          </div>
        } @else {
          <div class="grid gap-3">
            @for (task of filteredTasks(); track task.id) {
              <div
                [class.border-red-300]="task.overdue"
                [class.bg-red-50]="task.overdue"
                class="bg-white border rounded-xl p-4 shadow-sm hover:shadow-md
                       transition-shadow cursor-pointer"
                [routerLink]="['/tasks', task.id]">

                <!-- En-tête de la carte -->
                <div class="flex items-start justify-between gap-3">
                  <div class="flex-1 min-w-0">
                    <div class="flex items-center gap-2 flex-wrap mb-1">
                      <!-- Badge statut -->
                      <span [class]="getStatusColorClass(task.status)"
                            class="px-2 py-0.5 rounded-full text-xs font-medium">
                        {{ getStatusLabel(task.status) }}
                      </span>
                      <!-- Badge priorité -->
                      <span [class]="getPriorityColorClass(task.priority)"
                            class="px-2 py-0.5 rounded-full text-xs font-medium">
                        {{ getPriorityLabel(task.priority) }}
                      </span>
                      <!-- Badge retard -->
                      @if (task.overdue) {
                        <span class="px-2 py-0.5 bg-red-100 text-red-700 rounded-full
                                     text-xs font-medium">
                          ⚠️ En retard
                        </span>
                      }
                    </div>
                    <h3 class="font-semibold text-gray-900 truncate">{{ task.title }}</h3>
                    @if (task.description) {
                      <p class="text-sm text-gray-500 mt-0.5 line-clamp-1">{{ task.description }}</p>
                    }
                  </div>

                  <!-- Date d'échéance -->
                  @if (task.dueDate) {
                    <span [class.text-red-600]="task.overdue"
                          [class.text-gray-400]="!task.overdue"
                          class="text-xs whitespace-nowrap">
                      📅 {{ task.dueDate | date:'dd/MM/yy' }}
                    </span>
                  }
                </div>

                <!-- Motif de rejet -->
                @if (task.status === 'REJETEE' && task.rejectionReason) {
                  <div class="mt-2 p-2 bg-red-50 border border-red-100 rounded-lg">
                    <p class="text-xs text-red-700">
                      <strong>Motif :</strong> {{ task.rejectionReason }}
                    </p>
                  </div>
                }
              </div>
            }
          </div>
        }
      }
    </div>
  `,
})
export class TaskListComponent implements OnInit {

  // ── Services injectés ────────────────────────────────────────
  private readonly taskService = inject(TaskService);
  private readonly authService = inject(AuthService);

  // ── Signals — état local ─────────────────────────────────────
  readonly tasks        = signal<Task[]>([]);
  readonly loading      = signal(false);
  readonly error        = signal<string | null>(null);
  readonly filterStatus = signal<TaskStatus | null>(null);

  // ── Computed — dérivés réactifs ──────────────────────────────

  /** Tâches filtrées par statut actif */
  readonly filteredTasks = computed(() => {
    const status = this.filterStatus();
    return status ? this.tasks().filter(t => t.status === status) : this.tasks();
  });

  /** Nombre de tâches en retard */
  readonly overdueCount = computed(() => this.tasks().filter(t => t.overdue).length);

  // ── Computed depuis l'utilisateur connecté ───────────────────
  readonly isGestionnaire = this.authService.isGestionnaire;
  readonly canCreateTask  = this.authService.canCreateTask;

  // ── Constantes ───────────────────────────────────────────────
  readonly statuses: TaskStatus[] = ['A_FAIRE', 'VALIDEE', 'REJETEE', 'DONE'];

  // ── Cycle de vie ─────────────────────────────────────────────

  ngOnInit(): void {
    this.loadTasks();
  }

  reload(): void {
    this.loadTasks();
  }

  setFilter(status: TaskStatus | null): void {
    this.filterStatus.set(status);
  }

  countByStatus(status: TaskStatus): number {
    return this.tasks().filter(t => t.status === status).length;
  }

  getStatusLabel(status: TaskStatus): string {
    return TASK_STATUS_LABELS[status];
  }

  getStatusColorClass(status: TaskStatus): string {
    return TASK_STATUS_COLORS[status];
  }

  getPriorityLabel(priority: string): string {
    return PRIORITY_LABELS[priority as keyof typeof PRIORITY_LABELS] ?? priority;
  }

  getPriorityColorClass(priority: string): string {
    return PRIORITY_COLORS[priority as keyof typeof PRIORITY_COLORS] ?? '';
  }

  // ── Chargement des tâches ────────────────────────────────────

  private loadTasks(): void {
    this.loading.set(true);
    this.error.set(null);

    /**
     * Choix de l'endpoint selon le rôle :
     * → GESTIONNAIRE : /api/tasks/me (ses propres tâches)
     * → MANAGER      : /api/tasks?teamId=... (son équipe)
     * → SUPER_ADMIN  : /api/tasks?teamId=... ou /api/tasks (tout)
     */
    const user = this.authService.currentUser();
    const source$ = user?.role === 'GESTIONNAIRE'
      ? this.taskService.getMyTasks()
      : this.taskService.getTeamTasks(user?.teamId ?? '');

    source$.subscribe({
      next: tasks => {
        this.tasks.set(tasks);
        this.loading.set(false);
      },
      error: err => {
        this.error.set(err.message ?? 'Erreur lors du chargement des tâches');
        this.loading.set(false);
      },
    });
  }
}
